2024-04-29 00:12:01,405 - INFO - Using 16bit Automatic Mixed Precision (AMP)
2024-04-29 00:12:01,465 - INFO - GPU available: True (cuda), used: True
2024-04-29 00:12:01,684 - INFO - TPU available: False, using: 0 TPU cores
2024-04-29 00:12:01,684 - INFO - IPU available: False, using: 0 IPUs
2024-04-29 00:12:01,684 - INFO - HPU available: False, using: 0 HPUs
2024-04-29 00:12:01,717 - INFO - You are using a CUDA device ('NVIDIA GeForce RTX 4060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
2024-04-29 00:12:02,713 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-29 00:12:02,725 - INFO - 
  | Name  | Type     | Params
-----------------------------------
0 | model | ConvNeXt | 87.6 M
-----------------------------------
87.6 M    Trainable params
0         Non-trainable params
87.6 M    Total params
350.286   Total estimated model params size (MB)
2024-04-29 00:13:26,493 - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-04-29 00:13:27,390 - ERROR - "['val_loss', 'val_acc'] not in index"
Traceback (most recent call last):
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 532, in <module>
    test_loss, tess_acc, best_epoch = plot_results(monitor_value, f"{model_path}/{new_version}")
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/5.model.py", line 261, in plot_results
    val_results = log_results[['epoch', 'val_loss', 'val_acc']].dropna()
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4096, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/mnt/c/Users/ASUS/Downloads/Coding/ai-project3/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['val_loss', 'val_acc'] not in index"
